#!/bin/bash

IMAGE="scomet:v0.1"
MOUNT_DIR="/home/"
BUILD_CMD="cd /home/wjy/Pivot && python3 \$(which scons) build/X86/gem5.opt -j70"
KILL_CMD="pkill -f gem5.opt"

run_container() {
  local NAME=$1
  docker stop "$NAME" 2>/dev/null
  docker rm "$NAME" 2>/dev/null
  docker run -itd --name "$NAME" --user root --privileged -v "$MOUNT_DIR":"$MOUNT_DIR":rw "$IMAGE" /bin/bash
  docker exec -itd "$NAME" bash -c "$BUILD_CMD"
}

run_gem5() {
  local NAME=$1
  local N=$2
  local ENV=$3
  local CMD=$4
  local OPTS=$5
  local LLC=$6
  local L3C=$7
  local LAT=$8
  local OUT=$9

  docker exec -itd "$NAME" bash -c "cd /home/wjy/Pivot && \
  build/X86/gem5.opt configs/example/se.py \
  -n=$N --env='$ENV' \
  --cmd='$CMD' \
  --options=\"$OPTS\" \
  --cpu-type=X86O3CPU \
  --caches --l2cache --l3cache \
  --l1d_size=48kB --l1d_assoc=12 \
  --l1i_size=32kB --l1i_assoc=8 \
  --l2_size=2MB --l2_assoc=16 \
  --l3c_size=$L3C --l3c_assoc=$LLC \
  --l3b_size=8MB --l3b_assoc=1 \
  --mem-type=DDR5_6400_4x8 --mem-size=16GB --mem-channels=8 \
  --latency_critical_num=$LAT \
  --test_mode=MBA --MBACtrl=10% \
  > Results/$OUT"
}

MASSTREE_BIN="/home/wjy/Tailbench/tailbench/masstree/mttest_gem5se"
MASSTREE_OPTS="-j1 mycsba masstree -s1"

run_container scomet1
run_container scomet2
run_container scomet3
run_container scomet4
run_container scomet5

BE_BIN="/home/llj/dockerspec/benchspec/CPU/557.xz_r/run/run_base_refrate_mytest-m64.0000/xz_r_base.mytest-m64"
BE_OPTS="/home/llj/dockerspec/benchspec/CPU/557.xz_r/run/run_base_refrate_mytest-m64.0000/cld.tar.xz 160 19cf30ae51eddcbefda78dd06014b4b96281456e078ca7c13e1c0c9e6aaea8dff3efb4ad6b0456697718cede6bd5454852652806a657bb56e07d61128434b474 59796407 61004416 6"
BE_NAME="xz"

run_gem5 scomet1 32 "/home/wjy/Pivot/mastreeenv.txt" \
"$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$BE_BIN" \
"$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$BE_OPTS" \
14 "112MB" 31 "masstree_31_$BE_NAME.out"

BE_BIN="/home/llj/dockerspec/benchspec/CPU/523.xalancbmk_r/run/run_base_refrate_mytest-m64.0000/cpuxalan_r_base.mytest-m64"
BE_OPTS="-v /home/llj/dockerspec/benchspec/CPU/523.xalancbmk_r/run/run_base_refrate_mytest-m64.0000/t5.xml /home/llj/dockerspec/benchspec/CPU/523.xalancbmk_r/run/run_base_refrate_mytest-m64.0000/xalanc.xsl"
BE_NAME="xalancbmk"

run_gem5 scomet2 32 "/home/wjy/Pivot/mastreeenv.txt" \
"$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$BE_BIN" \
"$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$BE_OPTS" \
14 "112MB" 31 "masstree_31_$BE_NAME.out"

BE_BIN="/home/llj/dockerspec/benchspec/CPU/520.omnetpp_r/run/run_base_refrate_mytest-m64.0000/omnetpp_r_base.mytest-m64"
BE_OPTS="-c General -r 0"
BE_NAME="omnetpp"

run_gem5 scomet3 32 "/home/wjy/Pivot/mastreeenv.txt" \
"$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$BE_BIN" \
"$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$BE_OPTS" \
14 "112MB" 31 "masstree_31_$BE_NAME.out"

BE_BIN="/home/llj/dockerspec/benchspec/CPU/544.nab_r/run/run_base_refrate_mytest-m64.0000/nab_r_base.mytest-m64"
BE_OPTS="/home/llj/dockerspec/benchspec/CPU/544.nab_r/run/run_base_refrate_mytest-m64.0000/1am0 1122214447 122"
BE_NAME="nab"

run_gem5 scomet4 32 "/home/wjy/Pivot/mastreeenv.txt" \
"$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$BE_BIN" \
"$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$BE_OPTS" \
14 "112MB" 31 "masstree_31_$BE_NAME.out"

BE_BIN="/home/llj/dockerspec/benchspec/CPU/519.lbm_r/run/run_base_refrate_mytest-m64.0000/lbm_r_base.mytest-m64"
BE_OPTS="3000 /home/llj/dockerspec/benchspec/CPU/519.lbm_r/run/run_base_refrate_mytest-m64.0000/eference.dat 0 0 /home/llj/dockerspec/benchspec/CPU/519.lbm_r/run/run_base_refrate_mytest-m64.0000/100_100_130_ldc.of"
BE_NAME="lbm"

run_gem5 scomet5 32 "/home/wjy/Pivot/mastreeenv.txt" \
"$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$BE_BIN" \
"$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$BE_OPTS" \
14 "112MB" 31 "masstree_31_$BE_NAME.out"

# run_gem5 scomet2 4 "/home/wjy/Pivot/mastreeenv.txt" \
# "$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$BE_BIN" \
# "$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$BE_OPTS" \
# 7 "56MB" 3 "masstree_3_$BE_NAME.out"

# run_gem5 scomet3 8 "/home/wjy/Pivot/mastreeenv.txt" \
# "$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$MASSTREE_BIN;$BE_BIN" \
# "$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$MASSTREE_OPTS;$BE_OPTS" \
# 4 "32MB" 7 "masstree_7_$BE_NAME.out"

sleep 86400

for name in scomet1 scomet2 scomet3 scomet4 scomet5; do
  docker exec -itd "$name" bash -c "$KILL_CMD"
done
